<?xml version="1.0" encoding="utf-8"?><Database Name="BDWebLeo" Class="contextoTallerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=BDWebLeo;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BDWebLeoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HORASOCUPADAS" Member="HORASOCUPADAs">
    <Type Name="HORASOCUPADA">
      <Column Name="NOMBRE" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="APELLIDOS" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="MATRICULA" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="DNI" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="HORA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.usuariosYcontrasenas" Member="usuariosYcontrasenas">
    <Type Name="usuariosYcontrasena">
      <Column Name="Usuario" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.INSERTA_CLIENTES" Method="INSERTA_CLIENTES">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="APELLIDOS" Parameter="aPELLIDOS" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="MATRICULA" Parameter="mATRICULA" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DNI" Parameter="dNI" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="HORA" Parameter="hORA" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>