#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb.MiProyecto
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDWebLeo")]
	public partial class contextoTallerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public contextoTallerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDWebLeoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public contextoTallerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoTallerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoTallerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoTallerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HORASOCUPADA> HORASOCUPADAs
		{
			get
			{
				return this.GetTable<HORASOCUPADA>();
			}
		}
		
		public System.Data.Linq.Table<usuariosYcontrasena> usuariosYcontrasenas
		{
			get
			{
				return this.GetTable<usuariosYcontrasena>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.INSERTA_CLIENTES")]
		public int INSERTA_CLIENTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(30)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="NVarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATRICULA", DbType="NVarChar(30)")] string mATRICULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="NVarChar(30)")] string dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="NVarChar(30)")] string fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HORA", DbType="NVarChar(10)")] string hORA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDOS, mATRICULA, dNI, fECHA, hORA);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HORASOCUPADAS")]
	public partial class HORASOCUPADA
	{
		
		private string _NOMBRE;
		
		private string _APELLIDOS;
		
		private string _MATRICULA;
		
		private string _DNI;
		
		private string _FECHA;
		
		private string _HORA;
		
		public HORASOCUPADA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="NChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICULA", DbType="NChar(30)")]
		public string MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				if ((this._MATRICULA != value))
				{
					this._MATRICULA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NChar(30)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="NChar(30)")]
		public string FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA", DbType="NChar(10)")]
		public string HORA
		{
			get
			{
				return this._HORA;
			}
			set
			{
				if ((this._HORA != value))
				{
					this._HORA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuariosYcontrasenas")]
	public partial class usuariosYcontrasena
	{
		
		private string _Usuario;
		
		private string _Contrasena;
		
		public usuariosYcontrasena()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
